[package]
name = "iminversed/lightwork"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "default.project.json",
    "src/**",
    "src",
    "wally.toml",
    "README.md",
]
exclude = ["**"]

[dependencies]
Promise = "evaera/promise@4.0.0"